name: rulstm
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - ca-certificates
  - certifi
  - cffi
  - cudatoolkit
  - cudnn
  - intel-openmp
#  - libedit
  - libffi
#  - libgcc-ng
#  - libgfortran-ng
#  - libstdcxx-ng
  - mkl
  - mkl_fft
  - mkl_random
#  - ncurses
  - ninja
  - numpy
  - numpy-base
  - openssl
  - pip
  - pycparser
  - python
  - pytorch
#  - readline
  - setuptools
  - sqlite
  - tk
  - torchmetrics
  - wheel
  - xz
  - zlib
  - pip:
    - lmdb
    - pandas
    - python-dateutil
    - pytz
    - six
    - torch
    - tqdm
prefix: C:\users\oliver\anaconda3\envs\rulstm
